version: "3.7"
services:

  velocity_app:
    build:
      context: ./app
    networks:
      - envoymesh

  velocity_authz:
    build:
      context: ./authz
    networks:
      - envoymesh

  front-envoy:
    image: envoyproxy/envoy-alpine:v1.17-latest
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoymesh
    ports:
      - "8000:8000"

networks:
  envoymesh: {}
