on:
    push:
        branches:
            - master
            - main
        paths:
            - 'bbolt/**'
    pull_request:
        paths:
            - 'bbolt/**'
name: "Tests Bbolt"
jobs:
    Tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version:
                    - 1.19.x
                    - 1.20.x
                    - 1.21.x
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v4
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: '${{ matrix.go-version }}'
            -   name: Run Test
                run: cd ./bbolt && go test ./... -v -race
