on:
    push:
        branches:
            - master
            - main
        paths:
            - 'memory/**'
    pull_request:
        paths:
            - 'memory/**'
name: "Tests Local Storage"
jobs:
    Tests:
        strategy:
            matrix:
                go-version:
                    - 1.19.x
                    - 1.20.x
                    - 1.21.x
        runs-on: ubuntu-latest
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v4
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: '${{ matrix.go-version }}'
            -   name: Test Memory
                run: cd ./memory && go test ./... -v -race
