on:
    push:
        branches:
            - master
            - main
        paths:
            - 'mockstorage/**'
    pull_request:
        paths:
            - 'mockstorage/**'
name: "Tests Local Storage"
jobs:
    Tests:
        strategy:
            matrix:
                go-version:
                    - 1.21.x
                    - 1.22.x
        runs-on: ubuntu-latest
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v4
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: '${{ matrix.go-version }}'
            -   name: Test Mockstorage
                run: cd ./mockstorage && go test ./... -v -race
