on:
    push:
        branches:
            - master
            - main
        paths:
            - 'azureblob/**'
    pull_request:
        paths:
            - 'azureblob/**'
name: "Tests Azure Blob"
jobs:
    Tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version:
                    - 1.19.x
                    - 1.20.x
                    - 1.21.x
        steps:
        -   name: Install Azurite
            run: |
                docker run -d -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0 --blobPort 10000
        -   name: Fetch Repository
            uses: actions/checkout@v4
        -   name: Install Go
            uses: actions/setup-go@v5
            with:
                go-version: '${{ matrix.go-version }}'
        -   name: Run Test
            run: cd ./azureblob && go test ./... -v -race
