on:
    push:
        branches:
            - master
            - main
        paths:
            - 'mongodb/**'
    pull_request:
        paths:
            - 'mongodb/**'
name: "Tests Mongodb"
jobs:
    Tests:
        runs-on: ubuntu-latest
        services:
            mongo:
                image: 'mongo:latest'
                ports:
                    - '27017:27017'
        strategy:
            matrix:
                go-version:
                    - 1.19.x
                    - 1.20.x
                    - 1.21.x
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v4
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: '${{ matrix.go-version }}'
            -   name: Run Test
                run: cd ./mongodb && go test ./... -v -race

