on:
    push:
        branches:
            - master
            - main
        paths:
            - 'arangodb/**'
    pull_request:
        paths:
            - 'arangodb/**'
name: "Tests ArangoDB"
jobs:
    Tests:
        runs-on: ubuntu-latest
        services:
            arangodb:
                image: 'arangodb:latest'
                env:
                    ARANGO_NO_AUTH: 1
                ports:
                    - '8529:8529'
        strategy:
            matrix:
                go-version:
                    - 1.19.x
                    - 1.20.x
                    - 1.21.x
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v4
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: '${{ matrix.go-version }}'
            -   name: Run Test
                run: cd ./arangodb && go test ./... -v -race
