on:
    push:
        branches:
            - master
            - main
        paths:
            - 'memcache/**'
    pull_request:
        paths:
            - 'memcache/**'
name: "Tests Memcache"
jobs:
    Tests:
        runs-on: ubuntu-latest
        services:
            mongo:
                image: 'memcached:latest'
                ports:
                    - '11211:11211'
        strategy:
            matrix:
                go-version:
                    - 1.19.x
                    - 1.20.x
                    - 1.21.x
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v4
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: '${{ matrix.go-version }}'
            -   name: Run Test
                run: cd ./memcache && go test ./... -v -race
