on:
    push:
        branches:
            - master
            - main
        paths:
            - 'badger/**'
    pull_request:
        paths:
            - 'badger/**'
name: "Tests Badger"
jobs:
    Tests:
        strategy:
            matrix:
                go-version:
                    - 1.19.x
                    - 1.20.x
                    - 1.21.x
        runs-on: ubuntu-latest
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v4
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: '${{ matrix.go-version }}'
            -   name: Test Badger
                run: cd ./badger && go test ./... -v -race
