version: "3.9"
services:
  velocity-application:
    restart: always
    image: docker-mariadb-clean-arch:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - 8080:8080
    environment:
      - API_USERID=1
      - API_USERNAME=velocity
      - API_PASSWORD=velocity
      - JWT_SECRET=velocity
    networks:
      - application
    depends_on:
      - mariadb
    command: ./docker-mariadb-clean-arch

  mariadb:
    image: mariadb:10.6.3
    restart: always
    volumes:
      - ./scripts/migrations.sql:/docker-entrypoint-initdb.d/1.sql
    expose:
      - 3306
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    networks:
      - application

networks:
  application:
